### PR TITLE
README: remove /v2

### PR DESCRIPTION
**Pull request by lorin**
The install command didn't work for me without removing the `/v2`.

### CODE REVIEW

**Comment by peterbourgon** [comment]
The /v2 is important. What didn't work for you?

**Comment by lorin** [comment]
```
$  go get github.com/oklog/ulid/v2

package github.com/oklog/ulid/v2: cannot find package "github.com/oklog/ulid/v2" in any of:
	/usr/local/opt/go/libexec/src/github.com/oklog/ulid/v2 (from $GOROOT)
	/Users/lhochstein/.go/src/github.com/oklog/ulid/v2 (from $GOPATH)
```

```
$  go version
go version go1.14.2 darwin/amd64
```

**Comment by peterbourgon** [comment]
Ah, yeah, v2 and above require Go modules. Try this:

```
env GO111MODULE=on go get github.com/oklog/ulid/v2
```

**Comment by lorin** [comment]
That did it! 

```
$ env GO111MODULE=on go get github.com/oklog/ulid/v2

go: downloading github.com/oklog/ulid v1.3.1
go: downloading github.com/oklog/ulid/v2 v2.0.2
go: github.com/oklog/ulid/v2 upgrade => v2.0.2
```

**Comment by peterbourgon** [comment]
Great!

This env var is useful only for folks who are trying to get v2 or above, and only if they're doing it from a directory underneath their GOPATH. So I think it's fine to note in the description, but I wouldn't put it in the command block. Let me add a suggestion...

**Comment by lorin** [comment]
I'll close this PR for now.

**Comment by lorin** [comment]
Whoops, I missed that you were going to add it as a suggestion to this PR.

**Comment by peterbourgon** [comment]
Fixed this, I hope, in a different way.

**Pull request closed without merging**
