### PR TITLE
Use time.Time instead of Unix milliseconds

### PR DESCRIPTION
**Pull request by tw1nk**
@peterbourgon @tsenart This makes the API more pleasant to use.

### CODE REVIEW

**Comment by tw1nk** [comment]
CI failures seems to come from the environment variable $COVERALLS_TOKEN is not set.

**Comment by peterbourgon** [comment]
Did you run the benchmarks? How does this code compare, performance-wise, with the code it replaces?

**Comment by peterbourgon** [comment]
@tw1nk You can try rebasing to fix the build error. The questions remain :)

**Comment by peterbourgon** [comment]
Closing due to inactivity.

**Pull request closed without merging**
