### PR TITLE
cmd/ulid

### LINKED ISSUE #13: Standalone executable
Are you publishing a standalone executable for the `go` version? Someone asked over on my repo, and I wanted to send them your way, because doing it with `go` would be pretty straightforward.

### PR DESCRIPTION
**Pull request by peterbourgon**
Closes #13.

```
$ ulid -h
Usage: ulid [-hlqz] [-f <format>] [parameters ...]
 -f, --format=<format>  when parsing, show times in this format: default, rfc3339, unix, ms
 -h, --help             print this help text
 -l, --local            when parsing, show local time instead of UTC
 -q, --quick            when generating, use non-crypto-grade entropy
 -z, --zero             when generating, fix entropy to all-zeroes

$ ulid --quick
01C195CNZTBJ4MZDGF60D5Q384

$ ulid 01C195CNZTBJ4MZDGF60D5Q384
Thu Dec 14 00:04:38.522 UTC 2017

$ ulid -fms 01C195CNZTBJ4MZDGF60D5Q384
1513209878522

$ date ; ulid | xargs ulid
Wed Dec 13 16:18:45 PST 2017
Thu Dec 14 00:18:45.347 UTC 2017

$ date ; ulid | xargs ulid --local
Wed Dec 13 16:19:12 PST 2017
Wed Dec 13 16:19:12.571 PST 2017
```

### CODE REVIEW

**Comment by peterbourgon** [comment]
@alizain Does this meet your expectations?

@tsenart Thoughts?

**Comment by alizain** [comment]
@peterbourgon beautiful!!

quick question - a space between `-f` and the name of the format will work correctly as well?

```
$ ulid -f ms 01C195CNZTBJ4MZDGF60D5Q384
1513209878522
```

**Comment by peterbourgon** [comment]
Yes indeed.

**Comment by groob** [comment]
@peterbourgon anything blocking this PR? Would be great to get this as a utility.

**Comment by peterbourgon** [comment]
Oops!

**Comment by alizain** [comment]
🎉

**Pull request merged**
