### PR TITLE
Add sql value and scanning.

### PR DESCRIPTION
**Pull request by brycereitano**
@peterbourgon @tsenart Pulling in a simple implementation for scanning ulid in either string or binary formats. Letting it fall through to other methods that already handle length detection for any byte slice not `16` bytes long. 

Additionally, providing a `sql.Value` for inserting a binary format into a sql database.

Only thing debatable in this implementation. Is if we want to resort to string representation for `sql.Value`, as that will be properly handled by all database drivers. Where binary representation might not transmit properly.

### CODE REVIEW

**Comment by brycereitano** [comment]
The CI failure seems unrelated to my change.

**Comment by optiomas** [comment]
Should we aim for more compatibility with the Value() returning a string? What are the trade offs?

**Comment by brycereitano** [comment]
The main trade off is the size of the value you will store in the database. String representation would take 26 bytes over 16 bytes.

Pros:
- Easier to query by hand.
- Higher compatibility rate with database drivers.

Cons:
- Indexes take up more storage. (Data is cheap is a counter argument).
- Queries can take longer due to the longer key size.

**Comment by optiomas** [comment]
So why wouldn't users of this library create their own wrapper type for this, so choosing their own tradeoffs deliberately?

**Comment by brycereitano** [comment]
That is what I'm doing currently in my code, but having it available in the parent package is a big plus.

If the decision is to go with strings or not include it at all, I'll be continuing to use my wrapper type.

**Comment by brycereitano** [comment]
One less thing to think about really is the benefit. When attempting to scan a value in, and getting an error is an unideal situation for library users. That would be another plus to using strings, and they happen to use a database that doesn't support the binary protocol.

**Comment by optiomas** [comment]
> That is what I'm doing currently in my code, but having it available in the parent package is a big plus.

I'd rather keep it out since implementing this yourself isn't difficult and gives you the benefit of the choice above. This package favours configurability over ease of use.

**Comment by peterbourgon** [comment]
Closing as a consequence of the above conversation. But thanks for the patch!

**Comment by imaramos** [comment]
Just a question, I am storing this in postgres as bytea, I have tried to do encoding in order to be more readable to a human but I am not being able to do it. Shouldn't at least to be able to see the numeric value that the byte array represents?
Thank you

**Pull request closed without merging**
